from concurrent.futures import ThreadPoolExecutor,as_completed
import os,sys
sys.path.insert(0,os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config
from core.cache import get_cached_results,save_search_results,setup_database
from scrapers import get_scraper
def detect_category(query):
    q=query.lower()
        for key,data in config.CATEGORIES.items():
                if key=="all":continue
                        for kw in data.get('keywords',[]):
                                    if kw in q:return key
                                        return "all"
                                        def scrape_one_site(site_key,query):
                                            try:
                                                    s=get_scraper(site_key)
                                                            return s.scrape(query) if s else []
                                                                except Exception as e:
                                                                        print(f"Error {site_key}:{e}")
                                                                                return []
                                                                                def scrape_all_sites(query):
                                                                                    all_results=[]
                                                                                        with ThreadPoolExecutor(max_workers=len(config.SITES_TO_SCRAPE)) as ex:
                                                                                                futures={ex.submit(scrape_one_site,s,query):s for s in config.SITES_TO_SCRAPE}
                                                                                                        for f in as_completed(futures):
                                                                                                                    try:all_results.extend(f.result())
                                                                                                                                except:pass
                                                                                                                                    return all_results
                                                                                                                                    def rank_results(results):
                                                                                                                                        valid=[r for r in results if r.get('price',0)>0 and r.get('name','').strip()]
                                                                                                                                            valid.sort(key=lambda x:x.get('price',float('inf')))
                                                                                                                                                for i,r in enumerate(valid):
                                                                                                                                                        r['rank']=i+1
                                                                                                                                                                r['medal']=['🥇','🥈','🥉'][i] if i<3 else ''
                                                                                                                                                                    return valid[:config.MAX_RESULTS]
                                                                                                                                                                    def find_alternatives(results,query,category):
                                                                                                                                                                        if not results:return []
                                                                                                                                                                            lowest=results[0].get('price',0)
                                                                                                                                                                                if lowest<=0:return []
                                                                                                                                                                                    buf=config.PRICE_RANGE_BUFFER_PERCENT/100
                                                                                                                                                                                        lo,hi=lowest*(1-buf),lowest*(1+buf)
                                                                                                                                                                                            main_words=set(query.lower().split())
                                                                                                                                                                                                seen,alts=[],[]
                                                                                                                                                                                                    for r in results:
                                                                                                                                                                                                            name,price=r.get('name',''),r.get('price',0)
                                                                                                                                                                                                                    if not(lo<=price<=hi):continue
                                                                                                                                                                                                                            rw=set(name.lower().split())
                                                                                                                                                                                                                                    if main_words and rw and len(main_words&rw)/len(main_words)>0.6:continue
                                                                                                                                                                                                                                            key=name.lower()[:30]
                                                                                                                                                                                                                                                    if key in seen:continue
                                                                                                                                                                                                                                                            seen.append(key)
                                                                                                                                                                                                                                                                    alts.append({'name':name,'price':price,'site':r.get('site',''),'site_key':r.get('site_key',''),'site_logo':r.get('site_logo','🏪'),'url':r.get('url',''),'image':r.get('image',''),'price_diff':price-lowest})
                                                                                                                                                                                                                                                                            if len(alts)>=config.MAX_ALTERNATIVES:break
                                                                                                                                                                                                                                                                                return alts
                                                                                                                                                                                                                                                                                def format_price(price):
                                                                                                                                                                                                                                                                                    if not price or price<=0:return "Price not available"
                                                                                                                                                                                                                                                                                        return f"{config.CURRENCY} {int(price):,}"
                                                                                                                                                                                                                                                                                        def get_summary_stats(results):
                                                                                                                                                                                                                                                                                            if not results:return {}
                                                                                                                                                                                                                                                                                                prices=[r['price'] for r in results if r.get('price',0)>0]
                                                                                                                                                                                                                                                                                                    if not prices:return {}
                                                                                                                                                                                                                                                                                                        lo,hi=min(prices),max(prices)
                                                                                                                                                                                                                                                                                                            return {'lowest_price':lo,'highest_price':hi,'average_price':sum(prices)/len(prices),'savings':hi-lo,'savings_formatted':format_price(hi-lo),'lowest_formatted':format_price(lo),'highest_formatted':format_price(hi),'average_formatted':format_price(sum(prices)/len(prices)),'sites_count':len(set(r.get('site','') for r in results)),'results_count':len(results)}
                                                                                                                                                                                                                                                                                                            def search(query,category=None):
                                                                                                                                                                                                                                                                                                                setup_database()
                                                                                                                                                                                                                                                                                                                    query=query.strip()
                                                                                                                                                                                                                                                                                                                        if not query:return {'error':'Please enter a product','results':[],'alternatives':[]}
                                                                                                                                                                                                                                                                                                                            if not category or category=="all":category=detect_category(query)
                                                                                                                                                                                                                                                                                                                                cached=get_cached_results(query,category)
                                                                                                                                                                                                                                                                                                                                    if cached:
                                                                                                                                                                                                                                                                                                                                            results,alternatives,from_cache=cached['results'],cached['alternatives'],True
                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                        raw=scrape_all_sites(query)
                                                                                                                                                                                                                                                                                                                                                                results=rank_results(raw)
                                                                                                                                                                                                                                                                                                                                                                        alternatives=find_alternatives(raw,query,category)
                                                                                                                                                                                                                                                                                                                                                                                if results:save_search_results(query,results,alternatives,category)
                                                                                                                                                                                                                                                                                                                                                                                        from_cache=False
                                                                                                                                                                                                                                                                                                                                                                                            stats=get_summary_stats(results)
                                                                                                                                                                                                                                                                                                                                                                                                return {'query':query,'category':category,'category_info':config.CATEGORIES.get(category,config.CATEGORIES['all']),'results':results,'alternatives':alternatives,'stats':stats,'from_cache':from_cache,'total_results':len(results),'error':None}