from bs4 import BeautifulSoup
import sys,os
sys.path.insert(0,os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scrapers.base_scraper import BaseScraper
import config
class TelemartScraper(BaseScraper):
    def __init__(self):super().__init__("telemart")
        def scrape(self,query):
                results=[]
                        html=self.fetch_page(self.build_search_url(query))
                                if not html:return results
                                        soup=BeautifulSoup(html,'html.parser')
                                                cards=soup.find_all('div',{'class':lambda x:x and 'product' in str(x).lower()}) or soup.find_all('li',{'class':lambda x:x and 'item' in str(x).lower()})
                                                        for card in cards[:config.MAX_RESULTS]:
                                                                    try:
                                                                                    name_tag=card.find('a',title=True) or card.find('h2') or card.find('h3')
                                                                                                    if not name_tag:continue
                                                                                                                    name=name_tag.get('title','') or name_tag.get_text(strip=True)
                                                                                                                                    if not name:continue
                                                                                                                                                    price_tag=card.find('span',{'class':lambda x:x and 'price' in str(x).lower()})
                                                                                                                                                                    price=self.clean_price(price_tag.get_text(strip=True)) if price_tag else 0
                                                                                                                                                                                    if price<=0:continue
                                                                                                                                                                                                    link=card.find('a',href=True)
                                                                                                                                                                                                                    url=link.get('href','') if link else ""
                                                                                                                                                                                                                                    if url and not url.startswith('http'):url=self.base_url+url
                                                                                                                                                                                                                                                    img=card.find('img')
                                                                                                                                                                                                                                                                    image=img.get('src','') if img else ""
                                                                                                                                                                                                                                                                                    results.append(self.format_result(name,price,url,image))
                                                                                                                                                                                                                                                                                                except:continue
                                                                                                                                                                                                                                                                                                        return results
                                                                                                                                                                                                                                                                                                        class SymbiosScraper(BaseScraper):
                                                                                                                                                                                                                                                                                                            def __init__(self):super().__init__("symbios")
                                                                                                                                                                                                                                                                                                                def scrape(self,query):
                                                                                                                                                                                                                                                                                                                        results=[]
                                                                                                                                                                                                                                                                                                                                html=self.fetch_page(self.build_search_url(query))
                                                                                                                                                                                                                                                                                                                                        if not html:return results
                                                                                                                                                                                                                                                                                                                                                soup=BeautifulSoup(html,'html.parser')
                                                                                                                                                                                                                                                                                                                                                        cards=soup.find_all('div',{'class':lambda x:x and 'product' in str(x).lower()}) or soup.find_all('div',{'class':lambda x:x and 'item' in str(x).lower()})
                                                                                                                                                                                                                                                                                                                                                                for card in cards[:config.MAX_RESULTS]:
                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                            name_tag=card.find('h2') or card.find('h3') or card.find('a',title=True)
                                                                                                                                                                                                                                                                                                                                                                                                            if not name_tag:continue
                                                                                                                                                                                                                                                                                                                                                                                                                            name=name_tag.get('title','') or name_tag.get_text(strip=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                            if not name:continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                            price_tag=card.find('span',{'class':lambda x:x and 'price' in str(x).lower()})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            price=self.clean_price(price_tag.get_text(strip=True)) if price_tag else 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if price<=0:continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            link=card.find('a',href=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            url=link.get('href','') if link else ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if url and not url.startswith('http'):url=self.base_url+url
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            img=card.find('img')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            image=(img.get('src','') or img.get('data-src','')) if img else ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            results.append(self.format_result(name,price,url,image))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except:continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return results
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                class IShoppingScraper(BaseScraper):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def __init__(self):super().__init__("ishopping")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def scrape(self,query):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                results=[]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        html=self.fetch_page(self.build_search_url(query))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if not html:return results
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        soup=BeautifulSoup(html,'html.parser')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cards=soup.find_all('div',{'class':lambda x:x and 'product' in str(x).lower()}) or soup.find_all('li',{'class':lambda x:x and 'product' in str(x).lower()})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for card in cards[:config.MAX_RESULTS]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name_tag=card.find('h2') or card.find('h3') or card.find('a',title=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not name_tag:continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name=name_tag.get('title','') or name_tag.get_text(strip=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not name:continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    price_tag=card.find('span',{'class':lambda x:x and 'price' in str(x).lower()}) or card.find('div',{'class':lambda x:x and 'price' in str(x).lower()})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    price=self.clean_price(price_tag.get_text(strip=True)) if price_tag else 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if price<=0:continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    link=card.find('a',href=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    url=link.get('href','') if link else ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if url and not url.startswith('http'):url=self.base_url+url
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    img=card.find('img')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    image=(img.get('src','') or img.get('data-src','')) if img else ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    results.append(self.format_result(name,price,url,image))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except:continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return results